version: 2

builds:
  - main: ./cmd/willow
    binary: willow
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/iamrajjoshi/willow/internal/cli.version={{.Version}}

archives:
  - formats:
      - tar.gz
    name_template: "willow_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - name: willow
    repository:
      owner: iamrajjoshi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/iamrajjoshi/willow
    description: A simple, opinionated git worktree manager
    binaries:
      - willow

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
